# Generated by Django 5.1.2 on 2024-10-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
