# Generated by Django 4.2.9 on 2024-11-01 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0002_remove_newsarticle_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='title',
        ),
    ]
