# Generated by Django 4.2.9 on 2024-11-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0003_remove_newsarticle_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='details',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='news_type',
            field=models.CharField(max_length=100),
        ),
    ]
