# Generated by Django 4.2.9 on 2024-11-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0004_alter_newsarticle_details_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_type', models.CharField(max_length=100, unique=True)),
                ('templates', models.JSONField()),
            ],
        ),
    ]
