# Generated by Django 5.1.3 on 2024-11-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LLM', '0006_newsarticle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
    ]
